apiVersion: batch/v1
kind: CronJob
metadata:
  name: moon-collector
  namespace: astro

spec:
  schedule: "0 13 * * *"   # 05:00 MST
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          containers:
            - name: moon-collector
              image: xascker/moon-collector:0.11
              imagePullPolicy: IfNotPresent

              env:
                - name: APP_CONFIG
                  valueFrom:
                    secretKeyRef:
                      name: moon-properties
                      key: APP_CONFIG

              resources:
                requests:
                  cpu: "20m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"