FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["watchmedo", "auto-restart", "--recursive", "--patterns=*.py", "--", "python", "main.py"]
