apiVersion: v1
kind: Secret
metadata:
  name: poster-properties
  namespace: astro
type: Opaque

stringData:
  BOT_TOKEN: ""
  APP_CONFIG: |
    {
      "mongo_url": "mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/space?authSource=admin",
      "log_level": "DEBUG",
      "channel_id": "",
      "local_tz": "America/Edmonton"
    }